---
- name: Setup Spark Cluster
  hosts: cluster
  become: yes
  serial: 1  # Run on one host at a time to see errors clearly
  tasks:
    - name: Wait for SSH connectivity
      wait_for_connection:
        timeout: 30

    - name: Update package cache
      apt:
        update_cache: yes
      ignore_errors: yes

    - name: Install Java
      apt:
        name: openjdk-8-jdk-headless
        state: present
      ignore_errors: yes
      register: java_install

    - name: Debug Java installation
      debug:
        var: java_install

    - name: Check if Java was installed
      command: java -version
      register: java_version
      ignore_errors: yes

    - name: Show Java version
      debug:
        var: java_version